apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: webapp
        environment: dev
    spec:
      containers:
      - name: webapp
        image: asia.gcr.io/dius-158701/gke-webapp:v1
        ports:
        - containerPort: 80