apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    role: service
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    name: webapp
    tier: frontend